name: Build Clumsy (network-forward)

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v4

    - name: Patch divert.cpp
      run: |
        (Get-Content src\divert.cpp) -replace `
          'WINDIVERT_LAYER_NETWORK,', `
          'WINDIVERT_LAYER_NETWORK_FORWARD,' `
          | Set-Content src\divert.cpp

    - name: Set up Zig
      uses: goto-bus-stop/setup-zig@v2
      with:
        version: 0.12.0

    - name: Build (x64 Release)
      run: zig build -Drelease-fast -Dtarget=x86_64-windows-gnu

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: clumsy-network-forward
        path: |
          zig-out/bin/clumsy.exe
          third_party/WinDivert/x64/WinDivert64.dll
          third_party/WinDivert/x64/WinDivert64.sys
