# .github/workflows/build.yml
name: Build clumsy-network-forward

on:
  push:
    branches: [master]
  pull_request:

jobs:
  build:
    runs-on: windows-2022
    defaults:
      run:
        shell: pwsh

    steps:
    # 1. Check out the sources
    - uses: actions/checkout@v4

    # 2. Install Zig (same version you were using successfully)
    - uses: goto-bus-stop/setup-zig@v2
      with:
        version: 0.9.1
        cache: true

    # 3. Download and unzip WinDivert; -Force lets reruns overwrite
    - name: Fetch WinDivert 2.2.0-A
      run: |
        $url = "https://github.com/basil00/Divert/releases/download/v2.2.0/WinDivert-2.2.0-A.zip"
        Invoke-WebRequest $url -OutFile wd.zip
        Expand-Archive -Path wd.zip -DestinationPath external -Force

    # 4. Build clumsy
    - name: Build (x64 Release)
      run: zig build -Darch=x64 -Dconf=Release

    # 5. Copy the WinDivert runtime files next to the EXE
    - name: Bundle WinDivert runtime
      run: |
        $out   = Join-Path $env:GITHUB_WORKSPACE 'zig-out/bin'
        $src   = Join-Path $env:GITHUB_WORKSPACE 'external/WinDivert-2.2.0-A/x64'
        New-Item -ItemType Directory -Path $out -Force | Out-Null
        Copy-Item "$src\WinDivert.dll"  $out
        Copy-Item "$src\WinDivert64.sys" $out

    # 6. Upload artefact
    - uses: actions/upload-artifact@v4
      with:
        name: clumsy-network-forward
        path: zig-out/bin/*
