name: Build Clumsy (network-forward)

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-2022

    steps:
    # ────────────────────────────────────────────
    # 1. Checkout code
    - uses: actions/checkout@v4

    # ────────────────────────────────────────────
    # 2. Patch divert.c|cpp → NETWORK_FORWARD
    - name: Switch to NETWORK_FORWARD
      shell: pwsh
      run: |
        Get-ChildItem -Path src -Include divert.c,divert.cpp -File |
        ForEach-Object {
          (Get-Content $_) -replace 'WINDIVERT_LAYER_NETWORK,', `
                              'WINDIVERT_LAYER_NETWORK_FORWARD,' |
          Set-Content $_
        }

   # ────────────────────────────────────────────
   # 3. Download WinDivert 2.2-A headers + runtime
    - name: Download WinDivert
      shell: pwsh
      run: |
        $url = "https://github.com/basil00/Divert/releases/download/v2.2.0/WinDivert-2.2.0-A.zip"
        Invoke-WebRequest -Uri $url -OutFile wd.zip
        Expand-Archive -Path wd.zip -DestinationPath external -Force   # <─ add -Force

    # ────────────────────────────────────────────
    # 4. Install Zig 0.9.1 (matches build.zig API)
    - name: Set up Zig
      uses: goto-bus-stop/setup-zig@v2
      with:
        version: 0.9.1        # ← do not upgrade without touching build.zig

    # ────────────────────────────────────────────
    # 5. Build clumsy (x64 Release)
    - name: Build (x64 Release)
      run: zig build -Darch=x64 -Dconf=Release

    # ────────────────────────────────────────────
    # 6. Collect artefacts: clumsy.exe + WinDivert64.dll/sys
    - name: Collect artefacts
      shell: pwsh
      run: |
        New-Item -ItemType Directory -Path zig-out\bin -Force | Out-Null

        # Find the first matching DLL/SYS anywhere in the workspace
        $dll = Get-ChildItem -Path $Env:GITHUB_WORKSPACE -Recurse -Filter WinDivert64.dll | Select-Object -First 1
        $sys = Get-ChildItem -Path $Env:GITHUB_WORKSPACE -Recurse -Filter WinDivert64.sys | Select-Object -First 1

        Copy-Item $dll.FullName zig-out\bin\
        Copy-Item $sys.FullName zig-out\bin\

    # ────────────────────────────────────────────
    # 7. Upload artefact (EXE + DLL + SYS)
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: clumsy-network-forward
        path: zig-out/bin/*
