name: Build Clumsy (network-forward)

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v4

    # 1-line patch: switch WinDivert layer
    - name: Apply forward-layer patch
      run: |
        echo -e "diff --git a/src/divert.cpp b/src/divert.cpp\n@@\n-    divertHandle = WinDivertOpen(filter, WINDIVERT_LAYER_NETWORK, DIVERT_PRIORITY, 0);\n+    divertHandle = WinDivertOpen(filter, WINDIVERT_LAYER_NETWORK_FORWARD, DIVERT_PRIORITY, 0);" | git apply -

    # Set up the Zig compiler
    - name: Set up Zig
      uses: goto-bus-stop/setup-zig@v2
      with: { version: 0.12.0 }

    # Build 64-bit release binary
    - name: Build
      run: zig build -Drelease-fast -Dtarget=x86_64-windows-gnu

    # Publish the artefacts so you can download them
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: clumsy-network-forward
        path: |
          zig-out/bin/clumsy.exe
          third_party/WinDivert/x64/WinDivert64.dll
          third_party/WinDivert/x64/WinDivert64.sys
